# Generated by Django 3.0.7 on 2021-08-28 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('vaccination_type', models.CharField(max_length=30)),
                ('last_dose_date', models.DateField()),
                ('wechat', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('flight_land_date', models.DateField()),
                ('manual_override', models.CharField(choices=[('G', 'Green'), ('Y', 'Yellow'), ('R', 'Red'), ('U', 'Unknown')], max_length=1)),
            ],
        ),
    ]
