# Generated by Django 3.2.4 on 2021-08-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passageName', models.CharField(max_length=200)),
                ('pubDate', models.DateTimeField(verbose_name='date published')),
                ('catName', models.CharField(max_length=100)),
                ('passageId', models.IntegerField()),
            ],
        ),
    ]
