# Generated by Django 3.0.7 on 2021-09-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='last_test_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_test_result',
            field=models.CharField(blank=True, choices=[('N', 'Negative'), ('P', 'Positive')], max_length=1, null=True),
        ),
    ]
