# Generated by Django 3.0.7 on 2021-08-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='neighborhood_id',
            field=models.CharField(default=-1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='uuid',
            field=models.CharField(default=-1, max_length=50),
            preserve_default=False,
        ),
    ]
