# Generated by Django 3.0.7 on 2021-08-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210828_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='uuid',
        ),
        migrations.AddField(
            model_name='person',
            name='health_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='flight_land_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_dose_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='manual_override',
            field=models.CharField(blank=True, choices=[('G', 'Green'), ('Y', 'Yellow'), ('R', 'Red'), ('U', 'Unknown')], max_length=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='vaccination_type',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
