# Generated by Django 3.0.7 on 2021-09-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210907_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='last_dose_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='vaccination_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
