# Generated by Django 3.0.7 on 2021-08-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210828_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='revision',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='wechat',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
