# Generated by Django 3.0.7 on 2021-09-08 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20210908_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventscan',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Event'),
        ),
        migrations.AlterField(
            model_name='eventscan',
            name='override',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='eventscan',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Person'),
        ),
        migrations.AlterField(
            model_name='eventscan',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
