# Generated by Django 3.0.7 on 2021-08-31 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20210829_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='emaill_address',
            field=models.CharField(default='example@mail.com', max_length=50),
            preserve_default=False,
        ),
    ]
