# Generated by Django 3.0.7 on 2021-09-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20210908_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventscan',
            name='healthCodeColor',
            field=models.CharField(blank=True, choices=[('G', 'Green'), ('Y', 'Yellow'), ('R', 'Red'), ('U', 'Unknown')], max_length=1),
        ),
    ]
