# Generated by Django 3.0.7 on 2021-09-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_eventscan_healthcodecolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventscan',
            name='healthCodeColor',
            field=models.CharField(choices=[('G', 'Green'), ('Y', 'Yellow'), ('R', 'Red'), ('U', 'Unknown')], max_length=1),
        ),
    ]
